package com.example;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;

import com.example.treeview.test.OrgNode;
import com.example.treeview.test.OrgTreeAdapter;
import com.example.widget.R;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.util.ArrayList;
import java.util.List;

public class OrgTreeActivity extends AppCompatActivity {

    private List<OrgNode> mNodeList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_org_tree);
        initData();
       ListView listView =  findViewById(R.id.list_tree);

        try {
            OrgTreeAdapter orgTreeAdapter = new OrgTreeAdapter(listView,mNodeList,3);
            listView.setAdapter(orgTreeAdapter);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

    }

    private void initData() {
        mNodeList = new ArrayList<>();

        String result = getResult();
        Gson gson = new Gson();
        List<OrgNode> orgNodes = gson.fromJson(result, new TypeToken<List<OrgNode>>() {
        }.getType());

        mNodeList.addAll(orgNodes);

    }


    private String getResult(){
        return "[{\n" +
                "\t\"id\": 30,\n" +
                "\t\"no\": \"8016ce324bbb4279b9324247e9e2b56a\",\n" +
                "\t\"name\": \"博世科环保科技股份有限公司\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 0,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 114.316200,\n" +
                "\t\"latitude\": 30.581084,\n" +
                "\t\"version\": 3,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"1\"\n" +
                "}, {\n" +
                "\t\"id\": 35,\n" +
                "\t\"no\": \"bbe385e57fd2443e8a125f0007d4e0a8\",\n" +
                "\t\"name\": \"品运公司\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 30,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"2\"\n" +
                "}, {\n" +
                "\t\"id\": 36,\n" +
                "\t\"no\": \"2d13b9db903745558a0c6b989f50d5ef\",\n" +
                "\t\"name\": \"分子机构运营事业部\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 30,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 37,\n" +
                "\t\"no\": \"ab4b80157c094cb59a7381782c94dacf\",\n" +
                "\t\"name\": \"南宁内河项目运营经理部\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 35,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 38,\n" +
                "\t\"no\": \"5a3edae098a44ae293023da1600169f7\",\n" +
                "\t\"name\": \"直营项目运营经理部\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 35,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 39,\n" +
                "\t\"no\": \"fe2ac1f8b47a42a7a50d7a06d35f5414\",\n" +
                "\t\"name\": \"云南博世科运营部\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 36,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 40,\n" +
                "\t\"no\": \"6a3bbb006dde40c991b9897740cd97cd\",\n" +
                "\t\"name\": \"贺州公司运营部\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 36,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 41,\n" +
                "\t\"no\": \"b49333fa1dd148b68241d530c4d4883a\",\n" +
                "\t\"name\": \"湖南运博营世部科\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 36,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 42,\n" +
                "\t\"no\": \"7f42a652fdd946a18b5eff4f52398c4a\",\n" +
                "\t\"name\": \"全州公司\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 36,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 43,\n" +
                "\t\"no\": \"9553185b5b554d4abe798215fcd97942\",\n" +
                "\t\"name\": \"泗洪博世科\",\n" +
                "\t\"type\": 1,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 36,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 44,\n" +
                "\t\"no\": \"4459cf6378fa4e13bc67d8a1104c3a64\",\n" +
                "\t\"name\": \"横县项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 45,\n" +
                "\t\"no\": \"c3de5ebf28794beeaf71f0badc4d70e5\",\n" +
                "\t\"name\": \"合浦项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 46,\n" +
                "\t\"no\": \"243b6213d412474f8d8cb10697017138\",\n" +
                "\t\"name\": \"博白项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 47,\n" +
                "\t\"no\": \"86f6eced9653459f90c5a9821d0193e8\",\n" +
                "\t\"name\": \"大新项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 48,\n" +
                "\t\"no\": \"a7823ccc4f1a41cea1f64c02ad7a5a69\",\n" +
                "\t\"name\": \"崇左项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 49,\n" +
                "\t\"no\": \"09a08fb51d9041f0a5349e520615d8d7\",\n" +
                "\t\"name\": \"龙胜项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 50,\n" +
                "\t\"no\": \"9db21d6afa854c85a3b5ddb36a3fe155\",\n" +
                "\t\"name\": \"皇马项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 38,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 51,\n" +
                "\t\"no\": \"ff521df471834ceb93abea9790256344\",\n" +
                "\t\"name\": \"龙胜拉麻垃圾填埋场渗滤液处理站\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 49,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.960568,\n" +
                "\t\"latitude\": 25.804684,\n" +
                "\t\"version\": 3,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupz5OAEhlEAAGspB8qClQ603.jpg\",\n" +
                "\t\"description\": \"本处理站处理渗滤液量为70m³/d，处理工艺为UMAR-II厌氧+Fenton氧化+ MBR池+钠滤+反渗透，其主要生产构筑物为：调节池、预酸化池、UMARⅡ反应器、MBR池、中间水池、UHOFe氧化塔、中和脱气池。终沉池、多介质过滤器、纳滤系统、反渗透系统、污泥池、压滤机等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"97/99\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 52,\n" +
                "\t\"no\": \"8ff7f8e9013140c4889d66d68a2d6bdf\",\n" +
                "\t\"name\": \"钦州市钦北区（皇马）污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 50,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 108.627586,\n" +
                "\t\"latitude\": 22.053323,\n" +
                "\t\"version\": 4,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupz8KAUdUfAAG1k5KY-7o381.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为10000m³/d，处理工艺为UCT+SBR+过滤+消毒，其主要生产构筑物有：粗格栅及进水泵房、细格栅和旋流式沉砂池、UCT-SBR综合生化池、混凝及过滤池、紫外消毒渠、巴氏计量槽、鼓风机房和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"98/100\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": \"3\"\n" +
                "}, {\n" +
                "\t\"id\": 53,\n" +
                "\t\"no\": \"864de1b740304dd2812ac5d04addad9f\",\n" +
                "\t\"name\": \"富川项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 40,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 54,\n" +
                "\t\"no\": \"90e116faecf044279200db88e8b66faf\",\n" +
                "\t\"name\": \"富川县莲山污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 53,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.359722,\n" +
                "\t\"latitude\": 24.736388,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup0QOAKyS2AAmBuTSgGgE929.jpg\",\n" +
                "\t\"description\": \"处理规模为10000m³/d，处理工艺为改良型CASS(IBR)+D型滤池，主要生产构筑物有：提升泵站、调节池、细格栅、平流沉砂池、IBR生化池、D型滤池、污泥脱水间、紫外消毒池及巴氏计量槽、配电房、办公楼等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"101/104\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 55,\n" +
                "\t\"no\": \"a2c8f4bbcccd4da499907e88f2d0fb7c\",\n" +
                "\t\"name\": \"桂岭项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 40,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 56,\n" +
                "\t\"no\": \"94d46064a86f4c7d9a4ca0c062ada14b\",\n" +
                "\t\"name\": \"桂岭镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 55,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.804722,\n" +
                "\t\"latitude\": 24.673611,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup0U2AOQ9QAAh3fdNQ22I153.JPG\",\n" +
                "\t\"description\": \"处理规模为10000m³/d，处理工艺为CASS+滤池，主要生产构筑物有：提升泵站、应急池、细格栅、旋流沉砂池、CASS生化池、滤池、污泥脱水间、紫外消毒池及巴氏计量槽、维修间、配电房、办公楼等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"102/105\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 57,\n" +
                "\t\"no\": \"a34b87e12a7447f09871e7a63b01c869\",\n" +
                "\t\"name\": \"钟山项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 40,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": false,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 58,\n" +
                "\t\"no\": \"988a219525344bb2a98e5a85e9314ad6\",\n" +
                "\t\"name\": \"同古镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.215444,\n" +
                "\t\"latitude\": 24.378472,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup0xKAIl3zAAhShDBVYyE806.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/106\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 59,\n" +
                "\t\"no\": \"8605f953615244c28f15c18a5b00f13a\",\n" +
                "\t\"name\": \"回龙镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.288194,\n" +
                "\t\"latitude\": 24.442777,\n" +
                "\t\"version\": 2,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup00GALVi8AAcdiTUneTg830.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/107\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 60,\n" +
                "\t\"no\": \"d341a2b10a974a109d55b087a184d63d\",\n" +
                "\t\"name\": \"石龙镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.313111,\n" +
                "\t\"latitude\": 24.417722,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup0zeAOE2hAAYJZV-CzN8216.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/108\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 61,\n" +
                "\t\"no\": \"af96df587a864f6dab106fc76e63911f\",\n" +
                "\t\"name\": \"凤翔镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.362916,\n" +
                "\t\"latitude\": 24.382500,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup00uAOK66AAkhsjep_H8418.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/109\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 62,\n" +
                "\t\"no\": \"4ed67fe069c445dcb98ffea315ebf49b\",\n" +
                "\t\"name\": \"珊瑚镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.376027,\n" +
                "\t\"latitude\": 24.335944,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup01eAG85ZAAphlA8y8Qw461.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2、门卫室\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 63,\n" +
                "\t\"no\": \"2874603f8afa4e91884d1c3369222c6f\",\n" +
                "\t\"name\": \"红花镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.176444,\n" +
                "\t\"latitude\": 24.577055,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup02SAS_NXAAH5T3sBqBw476.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2、门卫室\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/110\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 64,\n" +
                "\t\"no\": \"0c81d87b06154d7f8d985f56301802bb\",\n" +
                "\t\"name\": \"花山瑶族乡污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.132888,\n" +
                "\t\"latitude\": 24.540888,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup05CAEfoCAATsUL_NDw4667.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井/调节池、污泥灌、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/111\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 65,\n" +
                "\t\"no\": \"7e17bd6efec540e78a60b40d3f7bac34\",\n" +
                "\t\"name\": \"两安瑶族乡污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.168000,\n" +
                "\t\"latitude\": 24.656361,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup06OANK2zAAH_RNaN-pU263.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/112\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 66,\n" +
                "\t\"no\": \"f94e3051c28c43dc8411bd489e4d7a4e\",\n" +
                "\t\"name\": \"燕塘镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.128027,\n" +
                "\t\"latitude\": 24.458833,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup08uAO5isAAHZOhme3q0304.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房1、管理用房2、门卫室\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/113\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 67,\n" +
                "\t\"no\": \"a5b1eaad31d74cc4b2e6b1e69ac1df87\",\n" +
                "\t\"name\": \"清塘镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 57,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.068416,\n" +
                "\t\"latitude\": 24.391361,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup09uARxKsAAcKKx7eYLY933.jpg\",\n" +
                "\t\"description\": \"处理规模为为500m³/d，主要生产构筑物有：配水井/格栅/提升井、调节池、污泥灌、配水器、ACM生物反应器、沉淀池、消毒渠、计量渠、管理用房2、\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"103/114\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 68,\n" +
                "\t\"no\": \"062c1ed732c14bdb8f9076d1c81079e2\",\n" +
                "\t\"name\": \"乌家镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 111.371478,\n" +
                "\t\"latitude\": 24.740198,\n" +
                "\t\"version\": 2,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupzvuAJJc8AAlQLwAfH8Y145.jpg\",\n" +
                "\t\"description\": \"总规模500m3/d，配套管网2公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 69,\n" +
                "\t\"no\": \"3218f436016344aa90fd256a49bdde98\",\n" +
                "\t\"name\": \"沙岗镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.050000,\n" +
                "\t\"latitude\": 21.674000,\n" +
                "\t\"version\": 2,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupzwiAK341AAL2pYycYwQ231.jpg\",\n" +
                "\t\"description\": \"总规模1000m3/d，配套管网2公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\\n联系人：梁德纲\\n联系电话：13978613286\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/116\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 70,\n" +
                "\t\"no\": \"27c82ddebe05433ba52a39b2407fb0ea\",\n" +
                "\t\"name\": \"石湾镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.231000,\n" +
                "\t\"latitude\": 21.766000,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupzyOAdT7FAAf5Hox6yCg549.jpg\",\n" +
                "\t\"description\": \"总规模500m3/d，配套管网2公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/117\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 71,\n" +
                "\t\"no\": \"8c64ba14efcf4427b62136d2518d6a94\",\n" +
                "\t\"name\": \"闸口镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.482000,\n" +
                "\t\"latitude\": 21.700000,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupzzWAODJSAAaWgN0LX9U737.jpg\",\n" +
                "\t\"description\": \"总规模500m3/d，配套管网1.5公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/118\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 72,\n" +
                "\t\"no\": \"e1d3749d4129414e92eaa36c8c852c06\",\n" +
                "\t\"name\": \"白沙镇第一污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.692000,\n" +
                "\t\"latitude\": 21.701000,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupz0aADI06AAWdI9WsSbc067.jpg\",\n" +
                "\t\"description\": \"总规模500m3/d，配套管网0.2公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/119\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 73,\n" +
                "\t\"no\": \"1801140517c84b689bfba19241e417ce\",\n" +
                "\t\"name\": \"白沙镇第二污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.689000,\n" +
                "\t\"latitude\": 21.709000,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": \"未建好\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/120\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 74,\n" +
                "\t\"no\": \"6261f5f4cb9e469cb6c11d7e41c4b593\",\n" +
                "\t\"name\": \"星岛湖镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.141000,\n" +
                "\t\"latitude\": 21.711000,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": \"未建好\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/121\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 75,\n" +
                "\t\"no\": \"90fad6a861c14036a4f40b9044eb820c\",\n" +
                "\t\"name\": \"沙田污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 45,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.662000,\n" +
                "\t\"latitude\": 21.519000,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupz16ATozWAAcnC6Ym8BQ296.jpg\",\n" +
                "\t\"description\": \"总规模500m3/d，配套管网1.7公里。其处理工艺为ACM生物反应器。其主要生产构筑物有格栅、调节池、配水器、ACM反应器、斜板沉淀池。紫外消毒渠、巴氏计量槽、储泥罐、综合用房等。\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"93/122\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 76,\n" +
                "\t\"no\": \"9db63bfb59294610926dd6aad5c8f508\",\n" +
                "\t\"name\": \"旺茂镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.904700,\n" +
                "\t\"latitude\": 22.099600,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFupz_-AGm8NAALbD3Oh3lg400.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为1000m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：机械格栅和集水井、粗格栅和调节池、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/123\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 77,\n" +
                "\t\"no\": \"6352d6c211cc48a2b13afef4bd402945\",\n" +
                "\t\"name\": \"沙河镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.707400,\n" +
                "\t\"latitude\": 22.050400,\n" +
                "\t\"version\": 3,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0CCALpUmAAHXH4RF8BU329.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为1500m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站2个、机械格栅和调节池、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\\n\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/124\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 78,\n" +
                "\t\"no\": \"537aebd2ee5b4b628af49fe8075c1dac\",\n" +
                "\t\"name\": \"顿谷镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.813600,\n" +
                "\t\"latitude\": 22.154300,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0DaANTbtAADqQRmkBRs415.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为500m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和调节池、、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/125\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 79,\n" +
                "\t\"no\": \"8cdaa7bb104c48ae82bc205cb534a014\",\n" +
                "\t\"name\": \"菱角镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.650300,\n" +
                "\t\"latitude\": 21.989800,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0E2APE4HAAD1ZdbhbNQ419.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为300m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和集水井、粗格栅和调节池、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/126\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 80,\n" +
                "\t\"no\": \"e77ee1dbab194bdd90bb8c43be5b0664\",\n" +
                "\t\"name\": \"径口镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 110.050200,\n" +
                "\t\"latitude\": 22.286300,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0F2AaVrIAAGqHTVxk4g096.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为500m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：机械格栅和集水井、粗格栅和调节池、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/127\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 81,\n" +
                "\t\"no\": \"2a6f48cdae154ba4bfabab47fabe1394\",\n" +
                "\t\"name\": \"水鸣镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.842300,\n" +
                "\t\"latitude\": 22.252800,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0HCAbXhDAB1ovajMxKM194.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为800m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和调节池、、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/128\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 82,\n" +
                "\t\"no\": \"62add125221c4d69874e9cddb19d7ba9\",\n" +
                "\t\"name\": \"永安镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.778100,\n" +
                "\t\"latitude\": 22.298500,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0ISAVBqGAAHpHXRaUQ0287.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为300m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和调节池、、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/129\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 83,\n" +
                "\t\"no\": \"6b35f312efb54c6a9a9853d418d78253\",\n" +
                "\t\"name\": \"那林镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.672900,\n" +
                "\t\"latitude\": 22.221100,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/00/CiIspFup0JiADgpyAAKOKuenSFM524.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为500m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和调节池、、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/131\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 84,\n" +
                "\t\"no\": \"9d7ad1bcfbcf46cfae1739fbdce1af63\",\n" +
                "\t\"name\": \"江宁镇污水处理厂\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 46,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": 109.617800,\n" +
                "\t\"latitude\": 22.150700,\n" +
                "\t\"version\": 1,\n" +
                "\t\"filePath\": \"http://122.114.164.162:16404/group1/M00/00/01/CiIspFup0KGAGAGSAAUhF5g4l9I194.jpg\",\n" +
                "\t\"description\": \"本污水处理厂第一期处理量为500m³/d，污水处理工艺采用ACM生物反应器（厌氧—接触氧化除磷脱氮生物膜反应器）+AEW人工湿地，其主要生产构筑物有：一体化泵站、机械格栅和调节池、、斜板沉淀池、人工湿地、紫外消毒渠、巴氏计量槽和污泥脱水间等\",\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 2,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"94/130\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}, {\n" +
                "\t\"id\": 122,\n" +
                "\t\"no\": \"62f78a4625814cc7b92e4cce4c2a757b\",\n" +
                "\t\"name\": \"泗洪项目\",\n" +
                "\t\"type\": 2,\n" +
                "\t\"tenantId\": 1,\n" +
                "\t\"fullName\": null,\n" +
                "\t\"address\": null,\n" +
                "\t\"tel\": null,\n" +
                "\t\"leader\": null,\n" +
                "\t\"parentId\": 43,\n" +
                "\t\"remarks\": null,\n" +
                "\t\"state\": 1,\n" +
                "\t\"longitude\": null,\n" +
                "\t\"latitude\": null,\n" +
                "\t\"version\": 0,\n" +
                "\t\"filePath\": null,\n" +
                "\t\"description\": null,\n" +
                "\t\"typeState\": \"2\",\n" +
                "\t\"extendsInfo\": \"[]\",\n" +
                "\t\"monitorState\": \"乡镇污水厂监视\",\n" +
                "\t\"count\": 0,\n" +
                "\t\"cameraUuid\": null,\n" +
                "\t\"processId\": \"\",\n" +
                "\t\"ifBottom\": true,\n" +
                "\t\"alarmName\": null,\n" +
                "\t\"staticType\": null\n" +
                "}]";
    }
}
